# Generated by Django 4.1.7 on 2023-02-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Websetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=255)),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_text', models.TextField()),
                ('learning_title', models.CharField(max_length=255)),
                ('work_title', models.CharField(max_length=255)),
                ('contact_title', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255)),
            ],
        ),
    ]
